version: "3.8"

services:
  db:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gateway_service
    volumes:
      - "bequest-db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  bequest-db:

networks:
  default:
      name: "bequest-local"
