// Code generated by mockery v2.10.6. DO NOT EDIT.

package pubsubMock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// Subscriber provides a mock function with given fields: ctx, callback
func (_m *Subscriber) Subscriber(ctx context.Context, callback func(context.Context, interface{}) error) error {
	ret := _m.Called(ctx, callback)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context, interface{}) error) error); ok {
		r0 = rf(ctx, callback)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
